### ISSUE TITLE
Low req per second, any way to fix this?

### ISSUE THREAD

**Issue by marcelo321** [ffuf/ffuf#158]
Hello!

I'm trying this amazing tool against a lot of domains and i noticed that in some domains it goes as a really high number of request per second (sometimes 300 or 2000 or 3000) and sometimes as low as 2 req/sec which makes my attack completely slow.

i noticed that i would have to add the -maxtime 360 option to not make it slow as fuck but i wanted to ask. Is there any way to speed this up? would speeding it up make more errors? i usually get 300-400 errors out of 6000 requests.

This is not a bug, it is a question.

**Comment by bjhulst** [comment]
@joohoi Would it go faster in general if this parameter in simple.go would be in the kilobyte range? //Download results < 5MB
const MAX_DOWNLOAD_SIZE = 5242880

**Comment by joohoi** [comment]
The behavior described in the original post is extremely context specific. It's more likely that there are some other issues causing the slowdown than large downloads. It's very easy to check and verify using curl / ffuf `-od` option. Also lowering the `MAX_DOWNLOAD_SIZE` will render many of the matchers / filters unreliable or unusable (because you cannot reliably use regex matching for content, cannot determine lines / words amounts from the content).

That said it might be beneficial to add a new CLI flag to a always skip downloading content, but it should come with a proper warning (and maybe erroring out if `-mw` / `-fw`, `-ml` / `-fl` is in use).

**Comment by bjhulst** [comment]
I could have a look at the implementation of that cli switch. If ok, what would the switch be called?

**Comment by joohoi** [comment]
> I could have a look at the implementation of that cli switch. If ok, what would the switch be called?

I created a new issue #178 to properly keep track on this work

**Comment by bjhulst** [comment]
FYI, I think this can be closed.

**Comment by mfaelbaz** [comment]
Change the VM adapter to bridged.
