### ISSUE TITLE
wrong results

### ISSUE THREAD

**Issue by Phoenix1112** [ffuf/ffuf#190]
hello.. In some scans, when I write status codes like -fc 403, no results are found.
But if I don't use the -fc parameter, some find directories that return 200 results.

ffuf -c -w /root/dirsearch/db/dicc.txt -u https://target.com/FUZZ -fc 403

not found

ffuf -c -w /root/dirsearch/db/dicc.txt -u https://target.com/FUZZ

favicon.ico
health
index.html
soap/
test/
test
soap

There are 20,000 words in my wordlist. When I use the -fc 403 parameter, the scanning process takes only 5 seconds. If I do not use the -fc 403 parameter, the program progresses more slowly and extracts directories with 200 status results. But after doing some research, I figured out why the problem was caused. this problem occurs if the -fc parameter is used after the -u parameter.

problematic screening:
-----------------------------

ffuf -c -w /root/dirsearch/db/dicc.txt -u https://target.com/FUZZ -fc 403

accurate scanning:
-------------------------

ffuf -c -w /root/dirsearch/db/dicc.txt -fc 403 -u https://target.com/FUZZ

There is a synchronization problem between the parameters. I detected another problem. I used the -fl parameter after the -fc parameter and it doesn't work.

problematic screening:
-----------------------------

ffuf -c -w /root/dirsearch/db/dicc.txt -fc 403 -fl 1 -u https://target.com/FUZZ

accurate scanning:
-------------------------

ffuf -c -w /root/dirsearch/db/dicc.txt -fl 1 -fc 403 -u https://target.com/FUZZ

If you do not correct such errors, people will get wrong results.

**Comment by joohoi** [comment]
I think there's something else going on in here. Most likely with either the host or your connection. Ffuf is using `flag` package from Go's standard library, and the resulting in-program configuration structure ends up being exactly the same regardless of the argument order.

Could you provide an endpoint where this is reproducable to some extent in order to figure out what's going on?

**Comment by Phoenix1112** [comment]
thank you for the answer. but this problem is not caused by go packages. I think the problem is caused by the lack of if and else queries. Here is a vivid example for you.

Now let's examine the command that makes the program work correctly.

command:
-------------
ffuf -c -w dirsearch/db/dicc.txt -u https://www.exodus.io/FUZZ -fc 400,403,404

output:
---------
![alt](https://imgur.com/IuN21DK.png)

Now let's examine the command that makes the program work correctly. We can see the result of "Lines: 1" in the results. now we will run the same command and filter the "Lines: 14" results. For this we will use the -fl 14 parameter.  Let's write the -fl parameter after the -fc parameter.

command:
--------------
ffuf -c -w dirsearch/db/dicc.txt -u https://www.exodus.io/FUZZ -fc 400,403,404 -fl 1

output:
---------
![alt](https://imgur.com/NbrlN7R.png)

again same command:
-----------------------------
![alt](https://imgur.com/qv9pHJF.png)

you can see the discrepancy between the results. but I couldn't show you the real proof I want to show. When I used the -fl 1 parameter before writing this message, there was no result. I used the -fl 1 parameter 2 or 3 times and the program ended without any results. But when I wanted to take a screenshot while writing this message, the -fl 1 parameter started working smoothly. I ran the program 3 times and the -fl 1 parameter produced correct results. so i couldn't take a screenshot. 
but when you look at the results above, there is still a mismatch.

**Comment by joohoi** [comment]
Thanks for posting the elaborate testing, it really helped to dig down to the core issue (especially the target used).

> thank you for the answer. but this problem is not caused by go packages. I think the problem is caused by the lack of if and else queries. Here is a vivid example for you.

I was merely suggesting that the issue was something in either your connection or server side. As regardless of the argument order on the command line, the ffuf configuration structure should be the same.

I was able to confirm the the issue, (or let's say feature) was indeed something on the server side. The server at exodus.io implements a rate limiting functionality that returns `429` results when it detects too many incoming requests in a short amount of time and this naturally leads to different results from run to run depending at which point the rate limiting triggers.

**Comment by joohoi** [comment]
I'm closing this issue as resolved. If you feel that there's still an outstanding issue, please comment and I'll reopen
