### ISSUE TITLE
response time

### ISSUE THREAD

**Issue by nongiach** [ffuf/ffuf#196]
Hello,

thank for this awesome tool.
Is there a way to filter/match or just get the response time for each request?
This would be great :)

Thank you.

**Comment by joohoi** [comment]
Thanks for your kind words!

It is definitely possible and I have considered implementing it as well. However the functionality would require a few more things to get actually meaningful results. First and foremost the concurrency often proves problematic with something like this. Ffuf would also need to make multiple identical requests in order to mitigate other anomalies, but this can again be problematic when there's caching in place (either in application, or reverse proxy level)

**Comment by nongiach** [comment]
Alright,
I only need to see if there is one abnormal time difference no need to have a precise measurement.
I didn't take a look at the code yet, but is there a lot of modification to be made to add a new column to the output and add time measurement for each requests?

Thank you.
___ @chaignc
