### ISSUE TITLE
[feature request] Ignore recursion for

### ISSUE THREAD

**Issue by dogasantos** [ffuf/ffuf#209]
In some cases, makes no sense to go into /images/, /css/, /static directories.
So would be nice to have an option to exclude certain paths from recursion

-recursion-exclusion=path1,path2,pathN

would it be possible?

Thanks

**Comment by joohoi** [comment]
Cheers! This is already possible by using regex filtering. 

In general, I wish to keep `ffuf` as swiss-army-knife-like tool as possible, and I prefer avoiding any context specific magic to it. Especially if something is achievable either in command line of `ffuf` itself or with a few lines of shell scripting around it. 

It's done in order to ensure that the tool stays useful in the vast amount of use cases it's currently good for as opposed to being strictly for example a content discovery tool.
