### ISSUE TITLE
-force-dns option and exampel of use case with virtual host bruteforce

### ISSUE THREAD

**Issue by noraj** [ffuf/ffuf#261]
ffuf can be used to find subdomains, one way to do it is like that:

```
ffuf -u http://FUZZ.example.org/ -r -c -w ~/CTF/tools/SecLists/Discovery/Web-Content/raft-large-words-lowercase.txt -mc 302 -ignore-body
```

But now if instead of example.org we have example.local, we put `10.0.0.1 example.local` in `/etc/hosts` but can't do it for each subdomain in the dictionary we want to use for bruteforce.

With FUZZ.example.local we will end in 100% of errors as no subdomains will be resolvable.

So what we need is a `-force-dns` (or similar name) option to tell to ffuf: "don't  try to resolve the names, instead assume it's this IP address"

So we would be able to do this:

```
ffuf -u http://FUZZ.example.local/ -r -c -w ~/CTF/tools/SecLists/Discovery/Web-Content/raft-large-words-lowercase.txt -mc 302 -ignore-body -force-dns 10.0.0.1
```

Of course it will be useful only if the subdomains are hosted with the same ip address, but this is quite common with virtual hosts.

So the `-force-dns` will allow to do virtual host bruteforce on local networks but can also bu useful in other scenarios.

**Comment by bsysop** [comment]
Hi @noraj, for VHOST enum you can do:

```
ffuf -u "http://10.0.0.1" -H "HOST: FUZZ.domain.com" -w wordlist
```

**Comment by noraj** [comment]
Hi @bsysop Thanks for you quick and accurate answer.

I was able to make it work this way:

```
ffuf -u http://10.0.0.1/ -r -c -w ~/CTF/tools/SecLists/Discovery/Web-Content/raft-small-words-lowercase.txt -H 'Host: FUZZ.example.org' -fs 800
```

But I'm sure there are maybe use cases where this can ends up useful what do you think?

**Comment by bsysop** [comment]
Hi @noraj, no problem! Here for help =]

**Technical:** FFUF focus is fuzzing HTTP protocol and DNS is just a step before (needed for any protocol works of course), you could find a lot of tools focused just in DNS, with parallelism, multiple resolvers, mutations, etc and maybe 5000x faster than FFUF for DNS resolver since it just works with your machine dns/resolver.

**Personal opinion:** Many others tools try to resolve all problems to researchers, and its great, but it limit the deepness of that tool, FFUF give you all the power you need, but focused in HTTP.

If you still consider it is a valid feature request, let this thread opened and we see what people thinks.

**Comment by noraj** [comment]
@bsysop Hum :thinking: I agree with your POV, I didn't think it that way before :thought_balloon:

**Comment by bsysop** [comment]
🤟🏻
