### ISSUE TITLE
Check for 403 response for every request

### ISSUE THREAD

**Issue by SolomonSklash** [ffuf/ffuf#3]
Great tool! The fastest I've tried for directory bruting.

One request I'd like to make is a check for every response returning a 403. I've seen other tools do is if almost every response is a 403, then they quit with a warning instead of going through the entire wordlist.

**Comment by joohoi** [comment]
Thanks for your kind words! Do you think that it would be important enough to add a new command line flag for it? 

I think there are many actual use cases where the user would want to keep hammering the service, for fuzzing some authentication headers for example. Because of this I'd like to keep the default as it is currently.

**Comment by codingo** [comment]
The standard for most tools is to default to not following a 403, and having a flag to do so. I'd definitely love to see  this as a feature / agree with having it as a flag.
