### ISSUE TITLE
Some what error

### ISSUE THREAD

**Issue by NightSling** [ffuf/ffuf#310]
![image](https://user-images.githubusercontent.com/32998571/94388280-445d6800-016c-11eb-9df2-37ebec3a7110.png)
Works with smaller wordlist

with big lists
![image](https://user-images.githubusercontent.com/32998571/94388296-5212ed80-016c-11eb-918b-a0aaad7fbad0.png)
Any solution??!!

**Comment by bjhulst** [comment]
If you are using the same list and the latest ffuf version, I cannot reproduce the error above. I do get other errors since the original file has the disclaimer/comments section still in place.
The list you have an error with is rather small.

$ wc -l SecLists/Discovery/Web-Content/directory-list-2.3-small.txt 
87664 SecLists/Discovery/Web-Content/directory-list-2.3-small.txt

$ ./ffuf -w SecLists/Discovery/Web-Content/directory-list-2.3-small.txt -u https://dummy.host.com/FUZZ

        /'___\  /'___\           /'___\       
       /\ \__/ /\ \__/  __  __  /\ \__/       
       \ \ ,__\\ \ ,__\/\ \/\ \ \ \ ,__\      
        \ \ \_/ \ \ \_/\ \ \_\ \ \ \ \_/      
         \ \_\   \ \_\  \ \____/  \ \_\       
          \/_/    \/_/   \/___/    \/_/       

       v1.2.0-git
________________________________________________

 :: Method           : GET
 :: URL              : https://dummy.host.com/FUZZ
 :: Wordlist         : FUZZ: SecLists/Discovery/Web-Content/directory-list-2.3-small.txt
 :: Follow redirects : false
 :: Calibration      : false
 :: Timeout          : 10
 :: Threads          : 40
 :: Matcher          : Response status: 200,204,301,302,307,401,403
________________________________________________

#                       [Status: 301, Size: 255, Words: 22, Lines: 4]
                        [Status: 301, Size: 255, Words: 22, Lines: 4]
# directory-list-2.3-small.txt [Status: 301, Size: 255, Words: 22, Lines: 4]
#                       [Status: 301, Size: 255, Words: 22, Lines: 4]
# on atleast 3 different hosts [Status: 301, Size: 255, Words: 22, Lines: 4]
# Priority ordered case sensative list, where entries were found [Status: 301, Size: 255, Words: 22, Lines: 4]
# Attribution-Share Alike 3.0 License. To view a copy of this [Status: 301, Size: 255, Words: 22, Lines: 4]
# Suite 300, San Francisco, California, 94105, USA. [Status: 301, Size: 255, Words: 22, Lines: 4]
#                       [Status: 301, Size: 255, Words: 22, Lines: 4]

I suggest upgrade to 1.2.0-git version of ffuf.

**Comment by joohoi** [comment]
Thanks for opening the issue!

This definitely is a bug, but only regarding the actual error.
This is the piece of code where it happens: https://github.com/ffuf/ffuf/blob/v1.1.0/main.go#L310-L314

This only happens when the following conditions are met:
 - You are running ffuf on Windows
 - The wordlist file does not exist
 - You did not define a custom keyword for the wordlist

I tagged this issue as bug, and will improve the windows corner cases there. However for you to fix this, the only thing you need to do is to define a wordlist file that actually exists.

**Comment by Haveyougonemad** [comment]
Tysm, Will  1.2.0-git version of ffuf work properly for me?

**Comment by Haveyougonemad** [comment]
and where do i download git-1.2.0

**Comment by bjhulst** [comment]
https://github.com/ffuf/ffuf/releases would be the place to get the latest release package but it is not placed there yet. (Alternatively you could build it from the source code.)

**Comment by Haveyougonemad** [comment]
> 
> 
> https://github.com/ffuf/ffuf/releases would be the place to get the latest release package but it is not placed there yet. (Alternatively you could build it from the source code.)

yea i did it is working now but i am not sure why isn't it displaying result when it gets a hit..

**Comment by yaswanthch20030324** [comment]
![image](https://user-images.githubusercontent.com/103668698/191533334-3a0f3221-af1d-4407-ba46-6ed3c5113da9.png)
why I am getting all errors
