### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-1]  

### ISSUE THREAD

**Issue by xothkug** [ffuf/ffuf#333]
Hi pretty new to github so tell me if im missing things. i installed ffuf on windows but everytime i try to run it with a url and wordlist file i get this error.

C:\Users\xxx>ffuf -u google.com/FUZZ/ -w test.com
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
main.prepareConfig(0xc0000cc000, 0xc000058d00, 0x4, 0x7)
        /home/joona/go/src/github.com/ffuf/ffuf/main.go:314 +0x26f2
main.main()
        /home/joona/go/src/github.com/ffuf/ffuf/main.go:143 +0x19fb

I googled it but cant come up with a solution
Thank you

**Comment by jimen0** [comment]
Hi @xothkug,

It indeed looks like a bug in the Windows wordlist path/keyword parsing logic. It would be nice if you could provide us with the following information:

- What exact ffuf version are you using? Do you know the release tag or the commit identifier from which it was built?
- What is `test.com` exactly on your system? `-w` flag is used to indicate a wordlist path (relative or absolute). Is it a relative path to a file named `test.com`?
- Could you please try again building ffuf from [`master:HEAD`](https://github.com/ffuf/ffuf/tree/602c1c79e8399ccae5f6f7d645ab4f8e47e77118) and tell us if the panic is still reproducible?

The panic is happening [here](https://github.com/ffuf/ffuf/blob/v1.1.0/main.go#L314):

https://github.com/ffuf/ffuf/blob/0633fb6b0aaa0332726e9b9d62c209846d1af78f/main.go#L314

This line was introduced by [this change](https://github.com/ffuf/ffuf/pull/240) cc @joohoi. The code panics because with input `test.com`, [`strings.LastIndex`](https://pkg.go.dev/strings#example-LastIndex) returns `-1` to indicate the substring is not present. Here's a reproducer: https://play.golang.org/p/SZ2dFsn5JU1.

Unfortunately, I don't have access to a Windows machine at the moment, but the error seems to come from the way Windows [wordlists paths/keywords are being parsed](https://github.com/ffuf/ffuf/blob/0633fb6b0aaa0332726e9b9d62c209846d1af78f/main.go#L305-L322).

**Comment by xothkug** [comment]
hi @jimen0

- i am using version 1.1. Im not sure what the "commit identifier" is? but i downloaded this one to be more exact 
  "ffuf_1.1.0_windows_amd64.zip"
- i noticed i should have put "text.txt" my bad. Either way i get the same response, its a text file with a few words to test ffuf 
  cause im still learning. Its in the same folder as my ffuf.exe.

- Idk how to build it? Could you explain.

Because you said it was introduced by a change i installed one version before that and it kinda worked. 
This is my command "ffuf -u http://codingo.io/FUZZ/ -w test.txt -o output.txt"
This is my response:
![Capture](https://user-images.githubusercontent.com/27363998/96368743-ee218a80-1155-11eb-8bdf-4a2b106daa2d.PNG)

Im not really understanding where it gets my wordlist like in what directory and how i have to specify it, cause i can only get it if its within the same folder. Also the output text file never gets created..

Thanks for helping

**Comment by jimen0** [comment]
Hi @xothkug,

Thank you for the additional information. I confirmed this is reproducible in `master` and `v1.1.0`, only on Windows systems and just when **the provided wordlist file does not exist**.

![image](https://user-images.githubusercontent.com/6826244/96372269-70b24600-1166-11eb-9c3d-d882aad2e45f.png)

Current `master` breaks exactly at the same place:

https://github.com/ffuf/ffuf/blob/602c1c79e8399ccae5f6f7d645ab4f8e47e77118/pkg/ffuf/optionsparser.go#L173-L186

The problem is not a big deal because ffuf works as expected when the provided wordlist exists. But still, ffuf should report an error instead of panicking. cc @joohoi 

Thank you for reporting @xothkug!

Best,
Miguel

**Comment by xothkug** [comment]
Ah okey thank you so much for helping :))

But can i ask how do i specify my locations for wordlists. Cause say my wordlist is one directory higher than my installation folder. When i do "./wordlist.txt" it doesnt find it.

But when i do "C:\Bug Bounty\--bb wordlists\objects-lowercase.txt" it also doesnt find it? Im not able to figure it out.

Thx

**Comment by jimen0** [comment]
Hi @xothkug,

You can traverse your file system tree by doing `../` to reach upper directories. Here's an example:

```console
$ tree -a /tmp/help
/tmp/help
├── a
└── b
    └── hello.txt

2 directories, 1 file
$ cat /tmp/help/b/hello.txt
Hey!
$ cd a
$ cat ../b/hello.txt
Hey!
```

[Here](https://swcarpentry.github.io/shell-novice/02-filedir/index.html) is a nice tutorial that might help you understanding this concept. 🚀

**Comment by xothkug** [comment]
Thank you so much, do i close the issue now?
