### ISSUE TITLE
unicode decode error

### ISSUE THREAD

**Issue by devcoinfet** [ffuf/ffuf#375]
:: Progress: [40/20469]'utf-8' codec can't decode byte 0xc2 in position 0: unexpected end of data

this is using this dict
 :: Wordlist         : FUZZ: /usr/share/wordlists/dirb/big.txt
 :: Follow redirects : false
 :: Calibration      : false

it seems to me there is an error with the tool handling wordlists with unicode in them

this is happening to all tools i use python and go for this i believe it may have something to do with upstream proxy responses
for countries that perhaps use unicode I can't confirm but i am suspicious this is the case due to personal setup.

**Comment by jimen0** [comment]
Hi @devcoinfet,

The error seems to come from the Python code you depend on.  Here you will find the error defined in Python standard library.

https://github.com/python/cpython/blob/ed1007c0d74e658d1e6c9b51b12ce7501eb8cbf9/Objects/exceptions.c#L2075

`ffuf` has no Python code, so the error isn't being caused by `ffuf` or Go. 

FYI @joohoi

**Comment by devcoinfet** [comment]
ok ill look into this not a surprise

**Comment by devcoinfet** [comment]
you were right thank you
