### ISSUE TITLE
ffuf won't recognize hyphenated fuzz keywords

### ISSUE THREAD

**Issue by bubby963** [ffuf/ffuf#425]
Hi,

Hopefully this isn't just me being stupid but when I try to run multiple fuzz keywords hyphenated (i.e. PARAM1-PARAM2) I get an error that says the keywords "defined, but not found in headers, method, URL or POST data." My command I am running is below:

ffuf -u "https://example.org/endpoint" -w "words.txt:HEAD1" -w "words.txt:HEAD2" -H "HEAD1-HEAD2: randomval" -fc 302  -c -o output.txt -of csv

Below is the image I get whenever I try to run it:

![errorimg](https://user-images.githubusercontent.com/3968863/114299774-18964400-9af8-11eb-9113-570b38b17797.PNG)

If I put a space so that it's -H "HEAD1 -HEAD2: randomval" however then it runs.

Any help you can offer with this would be much appreciated thanks!

**Comment by joohoi** [comment]
Hi, thanks for opening the issue! I looked into it and it definitely is a bug. It's caused by the internal canonicalization of the header keys when there's a hyphen involved.

While I'm figuring out the best way to fix it, the temporary workaround is to use wordlist variables that are canonicalized already, so using your command an example workaround would be:

```
ffuf -u "https://example.org/endpoint" -w "words.txt:Head1" -w "words.txt:Head2" -H "Head1-Head2: randomval" -fc 302 -c -o output.txt -of csv
```

**Comment by bubby963** [comment]
Thanks for taking the time to look into the issue! Glad to hear I wasn't just being dumb haha.

Thanks a lot for the workaround as well! Will use that for the time being until the bug is fixed.
