### ISSUE TITLE
W1 wordlist not feeding past first entry when using multiple lists

### ISSUE THREAD

**Issue by Dnozz** [ffuf/ffuf#504]
"username" wordlist isn't feeding properly. When I run this command: 

ffuf -w valid_usernames.txt:W1,/usr/share/wordlists/top-100.txt:W2 -X POST -d "username=W1&password=W2" -H "Content-Type: application/x-www-form-urlencoded" -u http://10.10.10.10/customers/login -fc 200

with names in valid_usernames.txt entered like:
steve
robert
admin
it never loads usernames past "steve". 
Seems the password.txt(W2) is working fine but when using multi lists, The W1 list doesnt feed past the first entry.

**Comment by joohoi** [comment]
This should work as expected, in case you are looking for the wordlists to run in lockstep, you need to use the multi-wordlist mode `pitchfork` instead of the `clusterbomb`, which tests all the combinations from w1 to w2, so in your example, all the passwords from passwords wordlist would be tested against first entry from the usernames wordlist, after which ffuf would move on to second entry from the users wordlist again testing all the passwords against that user.
