### ISSUE TITLE
keyword defined but not found error

### ISSUE THREAD

**Issue by distherapy** [ffuf/ffuf#505]
`./ffuf -u https://aaa.aaa.com -w /aaa/aaa/aaa/list.txt`

Encountered error(s): 1 errors occured.
	* Keyword FUZZ defined, but not found in headers, method, URL or POST data.

alternatively:

`./ffuf -u https://aaa.aaa.com -w /aaa/aaa/aaa/list.txt:HTTP`

Encountered error(s): 1 errors occured.
	* Keyword HTTP defined, but not found in headers, method, URL or POST data.

**ubuntu 20.04**

**Comment by bsysop** [comment]
Hi @distherapy 

You must set the KEYWORD in some part of the command.

Example:
```
./ffuf -u https://aaa.aaa.com/HTTP -w /aaa/aaa/aaa/list.txt:HTTP
./ffuf -u https://HTTP.aaa.com-w /aaa/aaa/aaa/list.txt:HTTP
```

or

```
./ffuf -u https://aaa.aaa.com/FUZZ -w /aaa/aaa/aaa/list.txt
./ffuf -u https://FUZZ.aaa.com-w /aaa/aaa/aaa/list.txt
```

Happy hacking.

**Comment by distherapy** [comment]
i have to put it twice? if you notice where it says alternatively i put:

`./ffuf -u https://aaa.aaa.com -w /aaa/aaa/aaa/list.txt:HTTP`

**Comment by bsysop** [comment]
In the follow command you have two parts.
```
./ffuf -u https://HTTP.aaa.com -w /aaa/aaa/aaa/list.txt:HTTP
```

### Part A: Wordlist keyword
`-w /aaa/aaa/aaa/list.txt:HTTP`

You selected a wordlist, in your case "/aaa/aaa/aaa/list.txt", then **ffuf** will itinerate word by word and send to somewhere to complete your fuzz.

Since you have added the `:HTTP` part at your wordlist file, you are defining that each word will be injected somewhere HTTP keyword appears (in Part B)

### Part B: Injection point
Now you have HTTP defined as wordlist keyword, you must defined WHERE ffuf will inject it.

```
./ffuf -u https://HTTP.aaa.com
./ffuf -u https://aaa.com/HTTP
./ffuf -u https://abc.aaa.com -H "Header: HTTP"
```

You can use it in many different ways.

Please let me know if is not clear.

**Comment by distherapy** [comment]
thank you

**Comment by bsysop** [comment]
You welcome
