### ISSUE TITLE
Version 2.0.0 output html file error 

### ISSUE THREAD

**Issue by test1278** [ffuf/ffuf#648]
Hi, Input: 
`./ffuf_2.0.0 -X GET -u http://www.google.com/FUZZ -w dicc/testWord.txt -mc all  -o  test.html -of html`
err:
`
[ERR] template: output.html:74:94: executing "output.html" at <$result.HTMLColor>: can't evaluate field HTMLColor in type output.htmlResult
`

**Comment by atikrahman1** [comment]
fetching the same error. Did you find any solution?

**Comment by atikrahman1** [comment]
The mention of this variable is here which seems to decide the color of an output based on the status code 

https://github.com/ffuf/ffuf/blob/e952deb061c0159f575214570fdf3144b4a29b65/pkg/output/file_html.go#L109

But it doesn't define the **HTMLColor** in  htmlResult structure that's why this error getting triggered 

https://github.com/ffuf/ffuf/blob/e952deb061c0159f575214570fdf3144b4a29b65/pkg/output/file_html.go#L12

```go
type htmlResult struct {
	Input            map[string]string
	Position         int
	StatusCode       int64
	ContentLength    int64
	ContentWords     int64
	ContentLines     int64
	ContentType      string
	RedirectLocation string
	ScraperData      string
	Duration         time.Duration
	ResultFile       string
	Url              string
	Host             string
	HTMLColor        string // Add this field
}
```

I fixed the issue by adding HTMLColor   string in the code and rebuild the package but the color based on status seems still not working.

**Comment by Hazegard** [comment]
Hi,

I submitted a pull request a few weeks ago that fixes this error and several other issues regarding the HTML output: https://github.com/ffuf/ffuf/pull/640

Waiting to be merged and released

**Comment by joohoi** [comment]
#640 is now merged, thanks for the fix! I'll close this issue for now, in case something is not working properly, please add a comment and I'll reopen the issue.

**Comment by hishammir** [comment]
@joohoi Hi ,
                  Im running the latest binary and still facing this issue.
![image](https://user-images.githubusercontent.com/30221965/227655184-7f39642b-9b0a-4706-a640-95dc29d281b5.png)
