### ISSUE TITLE
Using ffuf crashes my vm's network connectivity

### ISSUE THREAD

**Issue by behindblackwalls** [ffuf/ffuf#676]
Not sure what else to say, I hit about 1618 requests and they go through succcessfully then all my connectivity on that virtual machine crashes. It doesn't come back until I restart the VM. First I thought my ISP was throttling me but that wouldn't explain why a restart brings it back.

Are there any logs I can give that would help?

**Comment by bsysop** [comment]
Hi @NetRunnerBlackwall,

Sure

```
ffuf -debug-log your_debug_file.log [your arguments]
```

Then post it here :)

**Comment by behindblackwalls** [comment]
Hey, sorry I never did this! I've not had this issue in a while but if it pops up again I'll come back and post it.

**Comment by colinrubbert** [comment]
Did you ever get a resolution for this? 

I have the same issue, it happens with Feroxbuster, amass, or anything that is making a ton of fast network requests. It seems to bog down the nic. Wondering if you found a setting(s) that worked well to bypass this issue.

**Comment by bsysop** [comment]
Hi @colinrubbert, something is hard to debug.
I had issues with it in the past, then I bought better network devices but is possible that we are DoSing the ISP devices too 💀👀

**Comment by colinrubbert** [comment]
Hey @bsysop thanks for the response. I'll be honest, there's not much to look at in terms of debug logs as it just gets to a point where it just errors due to DNS can't handle the resolution. I've had similar issues with other connection-based tools. Here's a breakdown of my environments and some ruminasion:

Environment:
Env 1: W11 w/WSL2 Kali Linux (secondary)
Env 2: Kali Linux VM hosted on Unraid Server (primary)

Network:
1Gbps fiber to the house
1Gbps or 2.5Gbps internal networking

Hosts:
Personal Workstation (Env 1): Ryzen 7 2700x (8c/16t), 64GB DDR4, 2.5Gbps ethernet (runs at 1Gbps b/c networking is 1Gbps), RTX 2070
Unraid Server (Env 2): Intel Xeon Silver 4216 (16c/32t), 72GB DDR4 ECC, 2x 1Gbps ethernet (will probably add 4 more and give 2 dedicated lines to the Kali as fallbacks)

My theory is that this is a virtualized environment issue and not necessarily a FFuF issue. That being said, I think it would be good to explore or explain in the documentation why this could occur. I'm not even sure where exactly it's getting hung up: memory, virtual nic, flooding the DNS server, etc. I've allocated more than enough resource to this VM and when my VM's networking gets bogged down and can't make any more DNS requests, I can still make any DNS requests from a different VM on the same host machine or even straight from the host, including to the location I was attempting in my VM. Which pretty much tells us it's virtualized environment issue but again, why and where? 

I think the best thing to do is reduce the threads and rate when on a VM. I saw some good success at 9 threads with a rate of 10 req/s so it would roughly be 90 req/s. That's a far cry from the default 40 threads and whatever the default rate is which seems significantly higher than 10 req/s, I couldn't find the actual number quickly. 

Is there anything that you can think of within the code that would cause this or a good setting to go with?  A good [threads/rate : virtual_environment_resources] ratio formula, idk. 

Sorry, this is more rambly than helpful and I'm not sure that it's FFuF's fault at all. Thanks!

**Comment by JonLH22** [comment]
Coming here to say I have also encountered this issue. Seems like it's an VM thing. I used the above 9 threads and so far it's working well so I appreciate that. I guess that just means I'll have to be more patient. :) I might dig into it and see what's going on network wise, might be my ISP blocking it? As soon as I cancel it though internet on the VM works fine.
