### ISSUE TITLE
MATCHER OPTIONS no catch 201 by default

### ISSUE THREAD

**Issue by okitry** [ffuf/ffuf#715]
-mc                 Match HTTP status codes, or "all" for everything. (default: 200,204,301,302,307,401,403,405,500)

Today, I used FFUF to brute-force the variable name in a POST request, and I had an unsatisfactory result because it didn't catch 201 responses by default, and I didn't realize right away that the application might respond with 201 instead of 200.

**Comment by bsysop** [comment]
hi @okitry,
`-mc 200` does not include `201`, but it can included with `-mc 200,201,[...]`

Are you suggesting that 201 must be included by default? 

By the [RFC specification](https://www.rfc-editor.org/rfc/rfc9110#status.201):
---

[15.3.2. ](https://www.rfc-editor.org/rfc/rfc9110#section-15.3.2)[201 Created](https://www.rfc-editor.org/rfc/rfc9110#name-201-created)
The 201 (Created) status code indicates that the request has been fulfilled and has resulted in one or more new resources being created. The primary resource created by the request is identified by either a [Location](https://www.rfc-editor.org/rfc/rfc9110#field.location) header field in the response or, if no [Location](https://www.rfc-editor.org/rfc/rfc9110#field.location) header field is received, by the target URI.

The 201 response content typically describes and links to the resource(s) created. Any validator fields ([Section 8.8](https://www.rfc-editor.org/rfc/rfc9110#response.validator)) sent in the response convey the current validators for a new representation created by the request. Note that the PUT method ([Section 9.3.4](https://www.rfc-editor.org/rfc/rfc9110#PUT)) has additional requirements that might preclude sending such validators.

---

It's not a conventional HTTP status, mostly found when a resource is created, for example, a file upload or a user creation, since you were making a POST request, you was likely creating stuff, correct?

**Comment by bsysop** [comment]
Got it, interesting discussion!
Let's keep this open to see what Joo and other's say!

**Comment by joohoi** [comment]
All response codes definitely shouldn't be enabled per default (that's what `all` is for), but I do agree that having all `2XX` responses enabled by default could be a good idea. Want to create a PR for that @okitry to preserve "ownership" of the idea?
