### ISSUE TITLE
0 requests per second

### ISSUE THREAD

**Issue by kriptn** [ffuf/ffuf#758]
When I attempt to rerun a fuff command that I had to CTRL C . The second iteration runs with 0 requests per second. I am not sure how to address this.

**Comment by bsysop** [comment]
Hi @kriptn,
If you are saying the second time you scan the same server, it's probably because the server is dead or your IP was banned.
Please try with a different server, also lower number of threads is recommended.

If is not, please give some context and add some pictures.

Closing this for now, let me know if it needs something else.
Happy hacking.
